[package]
name = "oxypress_core"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
serde = {version = "1.0.228", features=["derive"]}
uuid = { version = "1.10", features = ["v4", "serde"] }


# Enable JS runtime support for getrandom only on WASM target
[target.'cfg(target_arch = "wasm32")'.dependencies]
uuid = { version = "1.10", features = ["js"] }

[build-dependencies]
chrono = "*"
