services:
  oxypress_web_server:
    image: oxypress_web_server
    build:
      context: .
      dockerfile: services/oxypress_web_server/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - oxypress_web_server_db
  oxypress_web_server_db:
    image: oxypress_web_server_db
    build:
      context: ./services/oxypress_web_server_db 
      dockerfile: ./Dockerfile
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data 
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER:-testdev}:${POSTGRES_PASSWORD:-testdev}@db:5432/${POSTGRES_DB:-oxypress_dev}
volumes:
  pgdata:
