services:
  oxypress_web_server:
    image: oxypress_web_server:dev
    build:
      target: dev
    environment:
      OXYPRESS_WEB_ROOT: "/oxypress/resources"
      OXYPRESS_WEB_ENABLE_LOGGING: "false"
      OXYPRESS_WEB_HTTP_PORT: "8080"
      OXYPRESS_WEB_HTTPS_PORT: "8081"
      OXYPRESS_WEB_CERT_DIRECTORY: "/etc/ssl/certs"
      OXYPRESS_DATABASE_URL: postgres://testdev:testdev@oxypress_web_server_db:5432/oxypress_dev
  oxypress_web_server_db:
    image: oxypress_web_server_db:dev
    environment:
      POSTGRES_USER: testdev
      POSTGRES_PASSWORD: testdev
      POSTGRES_DB: oxypress_dev
    build:
      target: dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testdev -d oxypress_dev"]
      interval: 2s
      timeout: 3s
      retries: 10
      start_period: 5s
