[env]
DOCKER_BUILDKIT=0

[tasks.sqlx-prepare-all]
workspace = false
dependencies = ["oxypress-prepare"]

[tasks.oxypress-prepare]
workspace = false
cwd = "./services/oxypress_web_server"
command = "cargo"
args = ["sqlx","prepare"]

[tasks.oxypress-sqlx]
cwd = "./services/oxypress_web_server_db"
workspace = false 
command = "cargo"
args = ["sqlx","${@}"]
description = "Enables you to call sqlx commands for oxypress from root"


[tasks.install-sqlx-cli]
workspace = false 
command = "cargo"
args = [
    "install", "sqlx-cli",
    "--version","0.8.0",
    "--target", "x86_64-unknown-linux-musl",
    "--no-default-features",
    "--features", "postgres,sqlx/tls-rustls"
]

[tasks.build-dev]
workspace = false
command = "docker"
args = [
    "compose",
    "-f", "docker-compose.base.yaml",
    "-f", "docker-compose.dev.yaml",
    "build"
]
dependencies = ['sqlx-prepare-all']
[tasks.dev]
workspace = false 
command = "docker"
args = [
    "compose",
    "-f", "docker-compose.base.yaml",
    "-f", "docker-compose.dev.yaml",
    "up","-d","--remove-orphans"
]
dependencies = ["gen-dev-certs",'build-dev']


[tasks.gen-dev-certs]
workspace = false
command = "cargo"
args = ["run", "-p","gen_local_certs"]

[tasks.build]
workspace = false
command = "docker"
args =["compose","build"]
dependencies = ["build-core","build-server","build-workspace"]

[tasks.build-workspace]
workspace = false
command = "cargo"
args = ["build"]

[tasks.build-core]
workspace = false
command = "cargo"
args = ["build", "-p", "oxypress_core", "--target", "x86_64-unknown-linux-musl"]

[tasks.run-oxypress-web]
workspace = false
dependencies = ["gen-dev-certs"]
description = "Runs the webserver, directly on the host machine, no sandboxing."
command = "cargo"
args = [
    "run",
    "-p", "oxypress_web_server",
    "--target",  "x86_64-unknown-linux-musl"
]

[tasks.run-oxypress-web.env]
OXYPRESS_WEB_ROOT = "./services/oxypress_web_server/resources"
OXYPRESS_WEB_ENABLE_LOGGING = "false"
OXYPRESS_WEB_HTTP_PORT = "8080"
OXYPRESS_WEB_HTTPS_PORT = "8081"
OXYPRESS_WEB_CERT_DIRECTORY = "./certs/dev"

[tasks.build-web-server]
workspace = false 
command = "cargo"
args = ["build", "-p", "oxypress_web_server", "--target", "x86_64-unknown-linux-musl"]

[tasks.clean]
workspace =false
command = "cargo"
args =[ "clean"]
dependencies =["docker-clean-images"]

[tasks.docker-clean-images]
workspace = false
script_runner = "bash"
description = "removes all oxypress images from disk"
script = '''
docker image ls | tr -s ' ' | grep -i 'oxypress' | cut -d' ' -f3 | xargs docker rmi -f 2> /dev/null & exit 0
'''
