[tasks.build]
workspace = false
command = "docker"
args =["compose","build"]
dependencies = ["build-core","build-server","build-workspace"]

[tasks.build-workspace]
workspace = false
command = "cargo"
args = ["build"]

[tasks.build-core]
workspace = false
command = "cargo"
args = ["build", "-p", "oxypress_core", "--target", "x86_64-unknown-linux-musl"]

[tasks.build-server]
workspace = false 
command = "cargo"
args = ["build", "-p", "oxypress_web_server", "--target", "x86_64-unknown-linux-musl"]

[tasks.clean]
workspace =false
command = "cargo"
args =[ "clean"]
dependencies =["docker-clean-images"]

[tasks.docker-clean-images]
workspace = false
script_runner = "bash"
description = "removes all oxypress images from disk"
script = '''
docker image ls | tr -s ' ' | grep -i 'oxypress' | cut -d' ' -f3 | xargs docker rmi -f 2> /dev/null & exit 0
'''

