[package]
name = "oxypress_server"
version = "0.1.0"
edition = "2024"

[dependencies]
oxypress_core = { path = "../oxypress_core" }
actix-web = { version = "4.11.0", features = ["rustls-0_23"] }
actix-files = { version ="0.6.8" }
env_logger = "0.11.8"
dotenvy = "0.15.7"
rustls = "0.23"
rustls-pemfile = "2"
backtrace = "0.3.75"
tokio = { version = "*", features = ["full"] }
chrono = "*"

[build-dependencies]
oxypress_core = { path = "../oxypress_core" }
tera = "1.20.0"
chrono = "*"
serde = "*"
